---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: command-runner
  namespace: flux-system
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: command-runner
  path: ./
  prune: true
  targetNamespace: command-runner
  dependsOn:
    - namespace: flagger
      name: flagger

