---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: command-runner
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./deploy
  prune: true
  sourceRef:
    kind: GitRepository
    name: command-runner
  targetNamespace: command-runner

