apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: command-runner
  namespace: command-runner
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: command-runner
  service:
    port: 8080
  analysis:
    interval: 1m
    threshold: 10
    maxWeight: 50
    stepWeight: 5
    metrics:
      - name: request-success-rate
        thresholdRange:
          min: 99
        interval: 1m
      - name: request-duration
        thresholdRange:
          max: 500
        interval: 1m
    webhooks:
      - name: load-test
        url: http://flagger-loadtester.command-runner/
        metadata:
          # cmd: "hey -z 1m -q 10 -c 2 http://command-runner:8080/"
          cmd: "curl -I http://command-runner.command-runner:8080/actuator/health"
