apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: command-runner
  namespace: command-runner
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: command-runner
  service:
    port: 8080
  analysis:
    interval: 30s
    threshold: 10
    maxWeight: 40
    stepWeight: 20
    metrics:
      - name: request-success-rate
        thresholdRange:
          min: 99
        interval: 30s
      - name: request-duration
        thresholdRange:
          max: 500
        interval: 30s
    webhooks:
      - name: load-test
        url: http://flagger-loadtester.command-runner/
        metadata:
          cmd: "hey -z 1m -q 10 -c 2 http://command-runner:8080/"
